SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
    JOIN ANIMAL_INS AI ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.DATETIME > AO.DATETIME
ORDER BY AI.DATETIME;

---------------------------------------------------------------------------------------

SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AO
    JOIN ANIMAL_INS AI ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE NOT AI.SEX_UPON_INTAKE = AO.SEX_UPON_OUTCOME
ORDER BY AO.ANIMAL_ID;
