SELECT * FROM FOOD_PRODUCT ORDER BY PRICE DESC LIMIT 1;

SELECT PRICE AS MAX_PRICE FROM PRODUCT ORDER BY PRICE DESC LIMIT 1;

SELECT MIN(DATETIME) AS '시간' FROM ANIMAL_INS;

SELECT COUNT(ANIMAL_ID) AS 'count' FROM ANIMAL_INS;

SELECT COUNT(DISTINCT NAME) AS 'count' FROM ANIMAL_INS;
