SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
    JOIN ANIMAL_INS AI ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.DATETIME > AO.DATETIME
ORDER BY AI.DATETIME;

---------------------------------------------------------------------------------------

SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AO
    JOIN ANIMAL_INS AI ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE NOT AI.SEX_UPON_INTAKE = AO.SEX_UPON_OUTCOME
ORDER BY AO.ANIMAL_ID;

---------------------------------------------------------------------------------------

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW R
    JOIN MEMBER_PROFILE M ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;

---------------------------------------------------------------------------------------

SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(DISTINCT UI.USER_ID) FROM USER_INFO UI WHERE YEAR(UI.JOINED)=2021), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE O
    JOIN USER_INFO U ON U.USER_ID = O.USER_ID AND YEAR(U.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
